name: RunBuddy
options:
  bundleIdPrefix: com.example
settings:
  base:
    PRODUCT_NAME: RunBuddy
    INFOPLIST_FILE: RunBuddy/Info.plist
targets:
  RunBuddy:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - RunBuddy
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.RunBuddy
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: RunBuddy/Info.plist
      properties:
        CFBundleDisplayName: RunBuddy
        NSCameraUsageDescription: RunBuddy needs camera access to capture images for text extraction.
        NSMicrophoneUsageDescription: RunBuddy needs microphone access to record speech for transcription.
        NSPhotoLibraryUsageDescription: RunBuddy needs photo library access to select images for text extraction.
        NSSpeechRecognitionUsageDescription: RunBuddy uses speech recognition to convert spoken English into text.
        UIRequiresFullScreen: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
    preBuildScripts: []
